/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lfenart.mastermind;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.List;

/**
 *
 * @author lfenart
 */
public class Game extends javax.swing.JPanel {

    private final Grid grid;

    /**
     * Creates new form Game
     */
    public Game() {
        this.grid = new Grid();
        initComponents();
    }
    
    public void play(Combination combination) {
        this.grid.play(combination);
        this.repaint();
    }

    private Color getColor(int color) {
        switch (color) {
            case 1:
                return Color.BLACK;
            case 2:
                return Color.BLUE;
            case 3:
                return Color.GRAY;
            case 4:
                return Color.GREEN;
            case 5:
                return Color.ORANGE;
            case 6:
                return Color.PINK;
            case 7:
                return Color.RED;
            case 8:
                return Color.YELLOW;
            default:
                return Color.WHITE;
        }
    }

    @Override
    public void paintComponent(Graphics g) {
        Graphics2D g2d = (Graphics2D) g;
        List<Combination> lines = this.grid.getLines();
        for (int i = 0; i < lines.size(); i++) {
            Combination line = lines.get(i);
            int[] colors = line.getColors();
            for (int j = 0; j < colors.length; j++) {
                g2d.setColor(getColor(colors[j]));
                g2d.fillOval(200 + 35 * j, 10 + 35 * i, 30, 30);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
